<h2>Roles</h2>
<?php
$titles = array(
            array('value' => 'ID'),
            array('value' => 'Role'),
            array('value' => 'Description'),
            array('value' => 'Access'),
        );
$table = array(
            'id' => 'acl_list',
            'class' => 'data'
        );
echo $this->table()->startTable($titles, $table);

$row = array();
foreach ($this->roles as $k => $v) {
    $access = array();
    foreach ($v->getRolePrivileges() as $k2 => $v2) {
        $access[] = $v2->getPrivilege_Id();
    }
    $row[] =
    array(
            array(
                'value' => $v->getId()
            ),
            array(
                'value' => $v->getName()
            ),
            array(
                'value' => $v->getDescription()
            ),
            array(
                'value' => implode(',', $access)
            )
        );
}
echo $this->table()->addRow($row);
echo $this->table()->endTable();