<h2>Roles</h2>
<?php
$titles = array(
            array('value' => 'ID'),
            array('value' => 'Role'),
            array('value' => 'Description'),
            array('value' => 'Access'),
        );
$table = array(
            'id' => 'acl_list',
            'class' => 'data'
        );
echo $this->table()->startTable($titles, $table);

$row = array();
foreach ($this->roles as $k => $v) {
    $row[] =
    array(
            array(
                'value' => $v->getId()
            ),
            array(
                'value' => $v->getName()
            ),
            array(
                'value' => $v->getDescription()
            ),
            array(
                'value' => var_dump($v->getPrivileges()->getPrivilege_Id()) #var_dump($v->getRolePrivileges()->getPrivilege_Id())
            )
        );
}
echo $this->table()->addRow($row);
echo $this->table()->endTable();