<?php
$titles = array(
            array('value' => 'Column 1'),
            array('value' => 'Column 2'),
            array('value' => 'Column 3'),
        );
$table = array(
            'id' => 'id_table_1',
            'class' => 'class_table_1 data'
        );
echo $this->table()->startTable($titles, $table);
$row = array(
    array(
        array(
            'id' => 'id_row_1a',
            'class' => 'class_row_1a',
            'value' => 'aaa111'
        ),
        array(
            'id' => 'id_row_1b',
            'class' => 'class_row_1b',
            'value' => 'aaa222'
        ),
        array(
            'id' => 'id_row_1c',
            'class' => 'class_row_1c',
            'value' => 'aaa333'
        )
    ),
    array(
        array(
                'id' => 'id_row_2a',
                'class' => 'class_row_2a',
                'value' => 'bbb111'
            ),
            array(
                'id' => 'id_row_2b',
                'class' => 'class_row_2b',
                'value' => 'bbb222'
            ),
            array(
                'id' => 'id_row_2c',
                'class' => 'class_row_2c',
                'value' => 'bbb333'
            )
        )
);
echo $this->table()->addRow($row);
echo $this->table()->endTable();