<?php $this->headLink()->appendStylesheet('/css/install.css'); ?>

<!-- Step 1: Pre-Setup checks -->
<div id="step_1">
	<h2>Pre-Setup checks</h2>
	<ul id="checks">
		<li class="<?php echo $this->phpVersion['class']; ?>">PHP-Version: <?php echo $this->phpVersion['value']; ?></li>
		<li class="<?php echo $this->mysqlVersion['class']; ?>">MySQL-Version: <?php echo $this->mysqlVersion['value']; ?></li>
		<li class="<?php echo $this->tmpWritable['class']; ?>">TMP-folder writable: <?php echo $this->tmpWritable['value']; ?></li>
	</ul>
</div>
<div id="forward">
	<a href="<?php echo $this->url(Array('module' => 'install', 'controller' => 'setup', 'action' => 'database')); ?>">Next step ></a>
</div>